apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: demo-mongodb-cluster-2
  namespace: mongodb
spec:
  members: 3
  version: 7.0.12-ent
  type: ReplicaSet
  # security:
  #   authentication:
  #     enabled: true
  #     modes: ["SCRAM"]
  opsManager:
    configMapRef:
      # Must match metadata.name in ConfigMap file
      name: my-project
  credentials: organization-secret
  persistent: true
  podSpec:
    podTemplate:
      spec:
       containers:
        - name: mongodb-enterprise-database
          resources:
            limits:
              cpu: 2
              memory: 2G
            requests:
              cpu: 1
              memory: 1G
            persistence:
              single:
                storage: 10Gi
---
# LoadBalancer Service for demo-mongodb-cluster-2-0
apiVersion: v1
kind: Service
metadata:
  name: demo-mongodb-cluster-2-0-lb
  namespace: mongodb
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: demo-mongodb-cluster-2-0  # Specific pod selector
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

---
# LoadBalancer Service for demo-mongodb-cluster-2-1
apiVersion: v1
kind: Service
metadata:
  name: demo-mongodb-cluster-2-1-lb
  namespace: mongodb
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: demo-mongodb-cluster-2-1  # Specific pod selector
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

---
# LoadBalancer Service for demo-mongodb-cluster-2-2
apiVersion: v1
kind: Service
metadata:
  name: demo-mongodb-cluster-2-2-lb
  namespace: mongodb
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: demo-mongodb-cluster-2-2  # Specific pod selector
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017