apiVersion: v1
stringData:
  FirstName: Tobias
  LastName: Joschko
  Password: qwes1MsZ$
  Username: tobias.joschko@mongodb.com
kind: Secret
metadata:
  creationTimestamp: null
  name: om-admin-secret
  namespace: mongodb
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: "mongodb"
spec:
  version: "7.0.8"
  # the name of the secret containing admin user credentials.
  adminCredentials: om-admin-secret
  externalConnectivity:
    type: LoadBalancer
  configuration:
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: mongodb
    mms.adminEmailAddr: support@example.com
    mms.fromEmailAddr: support@example.com
    mms.replyToEmailAddr: support@example.com
    mms.mail.hostname: example.com
    mms.mail.port: "465"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
  # the Replica Set backing Ops Manager.
  applicationDatabase:
    members: 3
    version: "7.0.12-ent"